{% set version = "0.9.6" %}
{% set github = "https://github.com/acidgenomics/r-pipette" %}

package:
  name: r-pipette
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: e04ec330c83928040c4e04eb4ec8a8b904bb8990873683c7f68cb39629f75afa

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    # Depends:
    - r-base >=4.1
    # Imports:
    - bioconductor-biocgenerics
    - bioconductor-biocio
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - r-acidbase >=0.5.0
    - r-acidcli >=0.2.0
    - r-acidgenerics >=0.6.0
    - r-data.table
    - r-goalie >=0.6.0
    - r-matrix
    - r-rcurl
    - r-readr
    - r-stringr
    - r-syntactic >=0.5.1
    - r-tibble
    # Suggests:
    - bioconductor-biocfilecache
    - bioconductor-biostrings
    - bioconductor-rtracklayer
    - r-digest
    - r-httr
    - r-jsonlite
    - r-pzfx
    - r-readxl
    - r-rio
    - r-stringi
    - r-yaml
  run:
    # Depends:
    - r-base >=4.1
    # Imports:
    - bioconductor-biocgenerics
    - bioconductor-biocio
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - r-acidbase >=0.5.0
    - r-acidcli >=0.2.0
    - r-acidgenerics >=0.6.0
    - r-data.table
    - r-goalie >=0.6.0
    - r-matrix
    - r-rcurl
    - r-readr
    - r-stringr
    - r-syntactic >=0.5.1
    - r-tibble
    # Suggests:
    - bioconductor-biocfilecache
    - bioconductor-biostrings
    - bioconductor-rtracklayer
    - r-digest
    - r-httr
    - r-jsonlite
    - r-pzfx
    - r-readxl
    - r-rio
    - r-stringi
    - r-yaml

test:
  commands:
    - $R -e "library('pipette')"

about:
  home: https://r.acidgenomics.com/packages/pipette/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Pipette biological data in and out of R.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
