{% set version="1.6.2" %}

package:
  name: flair
  version: {{ version }}

build:
  number: 0
  noarch: generic

source:
  url: https://github.com/BrooksLabUCSC/flair/archive/v{{ version }}.tar.gz
  sha256: 7824ef2968836838a84e5604458dde14c71b59725e15d10c9918aed02d36217f
  patches:                                                                                                                                                             
    - flair.patch
  
requirements:
  run:
    - python >=3.6
    - numpy
    - pandas
    - rpy2
    - tqdm
    - ncls
    - samtools
    - bedtools
    - pybedtools
    - minimap2
    - intervaltree
    - pysam >=0.16.0
    - r-ggplot2
    - r-qqman
    - bioconductor-deseq2
    - bioconductor-drimseq
    - bioconductor-stager
    - matplotlib-base
    - seaborn
    - kerneltree

test:
  commands:
    - flair.py --help 2>&1 | grep usage
    - flair.py align --help | grep usage
    - flair.py correct --help | grep usage
    - flair.py collapse --help | grep usage
    - flair.py quantify --help | grep usage
    - flair.py diffExp --help | grep usage
    - samtools --help | grep Usage

about:
  home: https://github.com/BrooksLabUCSC/flair
  license: BSD-3
  summary: Correction, isoform definition, and alternative splicing analysis of noisy reads (ONT and PacBio). 

extra:
  identifiers:
    - doi:10.1101/410183
