{% set name = "perl-text-csv" %}
{% set version = "2.02" %}
{% set sha256 = "84120de3e10489ea8fbbb96411a340c32cafbe5cdff7dd9576b207081baa9d24" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI/Text-CSV-2.02.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
    - perl-test-harness

  run:
    - perl
    - perl-test-harness

test:
  imports:
    - Text::CSV
    - Text::CSV_PP

about:
  home: http://metacpan.org/pod/Text::CSV
  license: perl_5
  summary: 'comma-separated values manipulator (using XS or PurePerl)'
