{% set version = "1.16" %}

package:
  name: samtools
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/samtools/samtools/releases/download/{{ version }}/samtools-{{ version }}.tar.bz2
  sha256: 6106b27fea5a6962cf5f257d68219e20235cce46039572afeff2c6cf11554764

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - htslib
    - ncurses
    - zlib
  run:
    - htslib
    - ncurses
    - zlib

about:
  home: https://github.com/samtools/samtools
  license: MIT
  license_file: LICENSE
  summary: Tools for dealing with SAM, BAM and CRAM files

test:
  commands:
    - samtools --help
    # test if https protocol works, if it doesnt samtools will fail with "Protocol not supported"
    - samtools view 'https://example.com' 2>&1 | grep 'fail to read the header' -q

extra:
  identifiers:
    - biotools:samtools
    - usegalaxy-eu:samtools_flagstat
