{% set name = "igv" %}
{% set version = "2.14.0" %}
{% set sha256 = "f3538ac6eb41e6627eb4d73b7b9d41f7d2cb978cb8df1e3e15ff270a8bf989e0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/igvteam/igv/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic

requirements:
  build:
    - openjdk >=11
  run:
    - openjdk >=11

test:
  commands:
    - igv --version
    - igv_hidpi --version

about:
  home: http://www.broadinstitute.org/software/igv/home
  license: MIT
  summary: |
    Integrative Genomics Viewer. Fast, efficient, scalable visualization tool for genomics
    data and annotations.

extra:
  identifiers:
    - biotools:igv
