{% set version = "0.6.3" %}
{% set github = "https://github.com/acidgenomics/r-acidgenerics" %}

package:
  name: r-acidgenerics
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 018783c6b38e01d84bcdab2a3ce88cdaa1f7ddde67b675e25e174aef0a7aa1eb

build:
  number: 0
  noarch: generic

requirements:
  host:
    - r-base >=4.2
  run:
    - r-base >=4.2

test:
  commands:
    - $R -e "library('AcidGenerics')"

about:
  home: https://r.acidgenomics.com/packages/acidgenerics/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: S4 generic functions for Acid Genomics packages.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
